// <auto-generated />
using System;
using MentorLink.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentorLink.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250327190336_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MentorLink.Data.Models.CapstoneWorkspace", b =>
                {
                    b.Property<int>("CapstoneWorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CapstoneWorkspaceId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkspaceCode")
                        .HasColumnType("longtext");

                    b.HasKey("CapstoneWorkspaceId");

                    b.ToTable("CapstoneWorkspaces");
                });

            modelBuilder.Entity("MentorLink.Data.Models.Lecturer", b =>
                {
                    b.Property<int>("LecturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LecturerId"));

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Experience")
                        .HasColumnType("longtext");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LecturerId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("MentorLink.Data.Models.LecturerWorkspace", b =>
                {
                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.HasKey("WorkspaceId", "LecturerId");

                    b.HasIndex("LecturerId");

                    b.ToTable("LecturerWorkspaces");
                });

            modelBuilder.Entity("MentorLink.Data.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CapstoneWorkspaceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGraduated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<string>("StudentCard")
                        .HasColumnType("longtext");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StudentId");

                    b.HasIndex("CapstoneWorkspaceId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MentorLink.Data.Models.TaskBoard", b =>
                {
                    b.Property<int>("TaskBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskBoardId"));

                    b.Property<int>("CapstoneWorkspaceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TaskBoardId");

                    b.HasIndex("CapstoneWorkspaceId");

                    b.ToTable("TaskBoards");
                });

            modelBuilder.Entity("MentorLink.Data.Models.LecturerWorkspace", b =>
                {
                    b.HasOne("MentorLink.Data.Models.Lecturer", "Lecturer")
                        .WithMany("LecturerWorkspaces")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentorLink.Data.Models.CapstoneWorkspace", "CapstoneWorkspace")
                        .WithMany("LecturerWorkspaces")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapstoneWorkspace");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("MentorLink.Data.Models.Student", b =>
                {
                    b.HasOne("MentorLink.Data.Models.CapstoneWorkspace", "CapstoneWorkspace")
                        .WithMany("Students")
                        .HasForeignKey("CapstoneWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapstoneWorkspace");
                });

            modelBuilder.Entity("MentorLink.Data.Models.TaskBoard", b =>
                {
                    b.HasOne("MentorLink.Data.Models.CapstoneWorkspace", "CapstoneWorkspace")
                        .WithMany("TaskBoards")
                        .HasForeignKey("CapstoneWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapstoneWorkspace");
                });

            modelBuilder.Entity("MentorLink.Data.Models.CapstoneWorkspace", b =>
                {
                    b.Navigation("LecturerWorkspaces");

                    b.Navigation("Students");

                    b.Navigation("TaskBoards");
                });

            modelBuilder.Entity("MentorLink.Data.Models.Lecturer", b =>
                {
                    b.Navigation("LecturerWorkspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
