// <auto-generated />
using System;
using MentorLink.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentorLink.Data.Migrations
{
    [DbContext(typeof(MentorLinkDbContext))]
    partial class MentorLinkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MentorLink.Data.Models.Capstoneworkspace", b =>
                {
                    b.Property<int>("CapstoneWorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CapstoneWorkspaceId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WorkspaceCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CapstoneWorkspaceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "WorkspaceCode" }, "WorkspaceCode")
                        .IsUnique();

                    b.ToTable("capstoneworkspace", (string)null);
                });

            modelBuilder.Entity("MentorLink.Data.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int>("Author")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Content")
                        .HasColumnType("json");

                    b.Property<DateTime?>("PublicDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UpdateStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("NewsId")
                        .HasName("PRIMARY");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("MentorLink.Data.Models.Taskboard", b =>
                {
                    b.Property<int>("TaskBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskBoardId"));

                    b.Property<int?>("CapstoneWorkspaceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("TaskBoardId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CapstoneWorkspaceId" }, "CapstoneWorkspaceId");

                    b.ToTable("taskboard", (string)null);
                });

            modelBuilder.Entity("MentorLink.Data.Models.Tasklist", b =>
                {
                    b.Property<int>("TaskListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskListId"));

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TaskBoardId")
                        .HasColumnType("int");

                    b.HasKey("TaskListId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TaskBoardId" }, "TaskBoardId");

                    b.ToTable("tasklist", (string)null);
                });

            modelBuilder.Entity("MentorLink.Data.Models.Taskboard", b =>
                {
                    b.HasOne("MentorLink.Data.Models.Capstoneworkspace", "CapstoneWorkspace")
                        .WithMany("Taskboards")
                        .HasForeignKey("CapstoneWorkspaceId")
                        .HasConstraintName("taskboard_ibfk_1");

                    b.Navigation("CapstoneWorkspace");
                });

            modelBuilder.Entity("MentorLink.Data.Models.Tasklist", b =>
                {
                    b.HasOne("MentorLink.Data.Models.Taskboard", "TaskBoard")
                        .WithMany("Tasklists")
                        .HasForeignKey("TaskBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tasklist_ibfk_1");

                    b.Navigation("TaskBoard");
                });

            modelBuilder.Entity("MentorLink.Data.Models.Capstoneworkspace", b =>
                {
                    b.Navigation("Taskboards");
                });

            modelBuilder.Entity("MentorLink.Data.Models.Taskboard", b =>
                {
                    b.Navigation("Tasklists");
                });
#pragma warning restore 612, 618
        }
    }
}
